/*Given a string, we have to find out all its subsequences of it. A String is a
subsequence of a given String, that is generated by deleting some character of a
given string without changing its order.*/
#include<iostream>
using namespace std;
void f(string str,int len, int idx=0,string curr=""){
    if (idx==len){
        cout<<curr<<" "; 
        return;
    }
    f(str,len,idx+1,curr+str[idx]);
    f(str,len,idx+1,curr);
}
int main(){
    string str ="abc";
    f(str,3);
    return 0;
}